from datetime import datetime
from enum import Enum as PyEnum
from sqlalchemy import (
    create_engine, Column, Integer, String, DateTime, Text, Boolean, 
    ForeignKey, Table, Index, func, Enum
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import TSVECTOR, UUID

# Database base class
Base = declarative_base()

# Enum for article types
class ArticleType(PyEnum):
    """Type of article - generated by LLM or handwritten."""
    GENERATED_NEWS = 'generated_news'   # LLM-generated news articles
    EDITORIAL = 'editorial'  # Your financial analysis, outlooks, discussions

# Association table for article-category many-to-many relationship
article_categories = Table(
    'article_categories',
    Base.metadata,
    Column('article_id', Integer, ForeignKey('articles.id', ondelete='CASCADE'), primary_key=True),
    Column('category_id', Integer, ForeignKey('categories.id'), primary_key=True)
)

# Association table for LLM metadata-source many-to-many relationship
llm_metadata_sources = Table(
    'llm_metadata_sources',
    Base.metadata,
    Column('article_id', Integer, ForeignKey('article_llm_metadata.article_id', ondelete='CASCADE'), primary_key=True),
    Column('source_id', Integer, ForeignKey('sources.id'), primary_key=True)
)

class Category(Base):
    """
    News categories (e.g., Politics, Technology, Sports).
    Used to organize articles into logical groups.
    """
    __tablename__ = 'categories'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(100), nullable=False, unique=True)
    
    # Relationships
    articles = relationship('Article', secondary=article_categories, back_populates='categories')

    def __repr__(self):
        return f"<Category(id={self.id}, name='{self.name}')>"

class Source(Base):
    """
    Sources represent websites that Gemini used during search/grounding
    to generate article content. Multiple sources can be associated with each LLM metadata record.
    """
    __tablename__ = 'sources'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    url = Column(String(500), nullable=False, unique=True)  # Full URL of the source
    domain = Column(String(100), nullable=False)  # Extract domain for easier querying
    
    # Relationships
    llm_metadata_records = relationship('ArticleLLMMetadata', secondary=llm_metadata_sources, back_populates='sources')

    def __repr__(self):
        return f"<Source(id={self.id}, domain='{self.domain}', url='{self.url[:50]}...')>"

class ArticleLLMMetadata(Base):
    """
    LLM generation metadata for news articles.
    Stores AI model info, sentiment score, and grounding sources for generated articles.
    Uses article_id as primary key for true 1:1 relationship.
    """
    __tablename__ = 'article_llm_metadata'
    
    article_id = Column(Integer, ForeignKey('articles.id', ondelete='CASCADE'), primary_key=True)
    ai_model_used = Column(String(50), nullable=False)
    sentiment_score = Column(Integer, nullable=False, default=0, server_default='0')  # Sentiment score (0-100)
    
    # Relationships
    article = relationship('Article', back_populates='llm_metadata')
    sources = relationship('Source', secondary=llm_metadata_sources, back_populates='llm_metadata_records')

class Article(Base):
    """
    Main article model containing news content.
    
    This model stores:
    - Article content and metadata
    - SEO optimization fields
    - Timestamps and status
    - Relationships to categories
    - LLM metadata (via llm_metadata relationship for generated articles)
    """
    __tablename__ = 'articles'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    title = Column(String(500), nullable=False)
    slug = Column(String(500), nullable=False, unique=True)
    excerpt = Column(Text, nullable=True)  # Short description/summary
    content = Column(Text, nullable=False)  # Generated article content
    thumbnail_url = Column(String(500), nullable=True)  # Local filename (e.g., 'article_123_abc.jpg')
    thumbnail_original_url = Column(String(500), nullable=True)  # Original provider URL (Freepik, Pexels, etc.)
    
    # Article status and workflow
    status = Column(String(20), default='published')  # draft, published, archived
    
    article_type = Column(
        Enum(ArticleType, name='article_type_enum', create_constraint=True),
        default=ArticleType.GENERATED_NEWS,
        nullable=False,
        server_default=ArticleType.GENERATED_NEWS.value
    )
    
    is_featured = Column(Boolean, default=False, nullable=False, server_default='false')
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    published_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    categories = relationship('Category', secondary=article_categories, back_populates='articles')
    llm_metadata = relationship('ArticleLLMMetadata', back_populates='article', uselist=False, cascade='all, delete-orphan')
    
    # Indexes for performance
    __table_args__ = (
        Index('idx_articles_published_at', 'published_at'),
        Index('idx_articles_slug', 'slug'),
        Index('idx_articles_article_type', 'article_type'),
        Index('idx_articles_is_featured', 'is_featured'),
    )

    def __repr__(self):
        return f"<Article(id={self.id}, title='{self.title[:50]}...', slug='{self.slug}')>"

    @property
    def is_published(self):
        """Check if article is published."""
        return self.status == 'published'

    @property
    def category_names(self):
        """Get list of category names for this article."""
        return [category.name for category in self.categories]

    @property
    def thumbnail(self):
        """Get thumbnail with fallback to original URL if local file is missing."""
        return self.thumbnail_url or self.thumbnail_original_url
