"""add_key_points_column_to_articles_metadata_table

Revision ID: 375889d8d02f
Revises: 3b978bd39913
Create Date: 2026-01-10 17:53:34.637833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '375889d8d02f'
down_revision: Union[str, Sequence[str], None] = '3b978bd39913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_llm_metadata', sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('article_llm_metadata', 'sentiment_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_llm_metadata', sa.Column('sentiment_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('article_llm_metadata', 'key_points')
    # ### end Alembic commands ###
