"""add_thumbnail_original_url_column_to_articles

Revision ID: 7c783e214029
Revises: ae1d76faf8ac
Create Date: 2025-12-28 12:20:35.835445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c783e214029'
down_revision: Union[str, Sequence[str], None] = 'ae1d76faf8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('thumbnail_original_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'thumbnail_original_url')
    # ### end Alembic commands ###
