"""add_cascade_delete_to_article_associations

Revision ID: 882c07dcb0c3
Revises: a1b2c3d4e5f6
Create Date: 2025-12-06 11:13:13.524681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882c07dcb0c3'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('article_categories_article_id_fkey'), 'article_categories', type_='foreignkey')
    op.create_foreign_key(None, 'article_categories', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('article_sources_article_id_fkey'), 'article_sources', type_='foreignkey')
    op.create_foreign_key(None, 'article_sources', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_sources', type_='foreignkey')
    op.create_foreign_key(op.f('article_sources_article_id_fkey'), 'article_sources', 'articles', ['article_id'], ['id'])
    op.drop_constraint(None, 'article_categories', type_='foreignkey')
    op.create_foreign_key(op.f('article_categories_article_id_fkey'), 'article_categories', 'articles', ['article_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
