"""add_sentiment_score_column_in_article_table

Revision ID: ae1d76faf8ac
Revises: 882c07dcb0c3
Create Date: 2025-12-07 17:44:40.055913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1d76faf8ac'
down_revision: Union[str, Sequence[str], None] = '882c07dcb0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('sentiment_score', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'sentiment_score')
    # ### end Alembic commands ###
